version: '3.8'

services:

  php:
    build: .docker/php
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www:cached
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=lc
      - POSTGRES_PASSWORD=lc
      - POSTGRES_DB=lc
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    external: true
